name: dart_html_dsl
description: A type-safe Dart DSL for building HTML, CSS, and JavaScript using pure Dart code, with scoped styles, pseudo-classes, and component-based architecture.
version: 0.0.3
repository: https://github.com/ThanCoder/dart_html_dsl

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
